server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mung_bean_cake_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20040901Zhj.

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pdd.mall.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 图片上传配置
app:
  image:
    upload-dir: uploads

logging:
  level:
    com.pdd.mall: debug
